name: Build and Release

on: workflow_dispatch  # manual trigger
  # push:
  #   branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: write  # allow to create a release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
        cache-dependency-path: "src/marco-polo/package-lock.json"
    - run: npm install
      working-directory: "src/marco-polo/"
    - run: make build
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: false
        prerelease: false
        title: "Marco-Polo Build"
        files: |
          dist/marco-polo.tgz
